services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    shm_size: 128mb
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    restart: unless-stopped

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
