services:
  # Overrides
  db:
    env_file:
      - ./env/backend.env
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager

  adminer:
    deploy:
      # 'Disable' adminer
      replicas: 0

  authentik-postgresql:
    env_file:
      - ./env/authentik.env
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager

  authentik-redis:
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager

  authentik-server:
    env_file:
      - ./env/authentik.env
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager

  authentik-worker:
    env_file:
      - ./env/authentik.env
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager

  minio:
    env_file:
      - ./env/minio.env
    deploy:
      # 'Disable' minio
      replicas: 0

  matomo-db:
    env_file:
      - ./env/matomo.env
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager

  matomo:
    env_file:
      - ./env/matomo.env
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager

  # Frontend
  frontend:
    image: ghcr.io/${GITHUB_REPOSITORY_OWNER:-freehunt}/freehunt-frontend:latest
    ports:
      - "5173:5173"
    deploy:
      replicas: 3

  # Backend
  backend:
    image: ghcr.io/${GITHUB_REPOSITORY_OWNER:-freehunt}/freehunt-backend:latest
    ports:
      - "3000:3000"
    env_file:
      - ./env/backend.env
    secrets:
      - minio_access_key
      - minio_secret_key
      - stripe_secret_key
      - stripe_webhook_secret
      - stripe_public_key

    deploy:
      replicas: 3

  # Production-only services
  uptime-kuma:
    container_name: uptime-kuma
    image: louislam/uptime-kuma:1.23.16-alpine
    ports:
      - 3002:3001
    volumes:
      - uptime-kuma-data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager

volumes:
  uptime-kuma-data:

secrets:
  minio_access_key:
    external: true
  minio_secret_key:
    external: true
  stripe_api_secret:
    external: true
  stripe_webhook_secret:
    external: true
