api:
  dashboard: true
  insecure: true

entryPoints:
  web:
    address: ":80"

providers:
  swarm:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    watch: true

log:
  level: INFO
