name: Node.js CI/CD

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  test-backend:
    if: github.event_name == 'pull_request' || github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    name: Run backend tests

    defaults:
      run:
        working-directory: backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: "npm"
          cache-dependency-path: backend/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Run unit tests
        run: npm test

  test-frontend:
    if: github.event_name == 'pull_request' || github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    name: Run frontend tests

    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: "npm"
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Check TypeScript types
        run: npx tsc --noEmit

      - name: Run ESLint
        run: npm run lint

  build-frontend:
    name: Build and push frontend
    needs: [test-frontend]
    if: (github.event_name == 'push' && github.ref == 'refs/heads/main') || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://freehunt.fr

    # Set permissions needed for GITHUB_TOKEN to push to GHCR
    permissions:
      contents: read
      packages: write
      security-events: write

    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up Docker Buildx for better caching and multi-platform support
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Set up QEMU for multi-platform builds
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # Login to GitHub Container Registry using GITHUB_TOKEN
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Extract metadata for Docker image
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/freehunt-frontend
          tags: |
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' }}
            type=sha,format=long
            type=semver,pattern={{version}},enable=${{ startsWith(github.ref, 'refs/tags/v') }}
            type=semver,pattern={{major}}.{{minor}},enable=${{ startsWith(github.ref, 'refs/tags/v') }}
            type=ref,event=branch
            type=ref,event=pr

      # Cache npm dependencies to speed up builds
      - name: Cache npm dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.npm
            frontend/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('frontend/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # Build and push Docker image with proper error handling
      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          platforms: linux/amd64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            NEXT_PUBLIC_API_URL=${{ vars.NEXT_PUBLIC_API_URL }}
            NEXT_PUBLIC_MATOMO_URL=${{ vars.NEXT_PUBLIC_MATOMO_URL }}
            NEXT_PUBLIC_MATOMO_SITE_ID=${{ vars.NEXT_PUBLIC_MATOMO_SITE_ID }}

  build-backend:
    name: Build and push backend
    needs: [test-backend]
    if: (github.event_name == 'push' && github.ref == 'refs/heads/main') || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://freehunt.fr

    # Set permissions needed for GITHUB_TOKEN to push to GHCR
    permissions:
      contents: read
      packages: write
      security-events: write

    defaults:
      run:
        working-directory: backend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up Docker Buildx for better caching and multi-platform support
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Set up QEMU for multi-platform builds
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # Login to GitHub Container Registry using GITHUB_TOKEN
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Extract metadata for Docker image
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/freehunt-backend
          tags: |
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' }}
            type=sha,format=long
            type=semver,pattern={{version}},enable=${{ startsWith(github.ref, 'refs/tags/v') }}
            type=semver,pattern={{major}}.{{minor}},enable=${{ startsWith(github.ref, 'refs/tags/v') }}
            type=ref,event=branch
            type=ref,event=pr

      # Cache npm dependencies to speed up builds
      - name: Cache npm dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.npm
            backend/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('backend/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # Build and push Docker image with proper error handling
      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          platforms: linux/amd64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            AUTHENTIK_URL=${{ vars.AUTHENTIK_URL }}
            FRONTEND_URL=${{ vars.FRONTEND_URL }}
            S3_URL=${{ vars.S3_URL }}

  sync-secrets:
    name: Sync Docker Swarm secrets
    needs: [build-frontend, build-backend]
    if: (github.event_name == 'push' && github.ref == 'refs/heads/main') || github.event_name == 'workflow_dispatch'
    runs-on: self-hosted
    environment:
      name: production
      url: https://freehunt.fr

    steps:
      - name: Sync secrets to Docker Swarm
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Create Docker Swarm secrets (skip if already exists)
            create_secret_if_not_exists() {
              local secret_name=$1
              local secret_value=$2
              
              if docker secret inspect "$secret_name" >/dev/null 2>&1; then
                echo "Secret $secret_name already exists, skipping..."
              else
                echo "$secret_value" | docker secret create "$secret_name" -
                echo "Created secret: $secret_name"
              fi
            }

            # Backend secrets
            create_secret_if_not_exists "database_url" "${{ secrets.DATABASE_URL }}"
            create_secret_if_not_exists "backend_postgres_password" "${{ secrets.POSTGRES_PASSWORD }}"

            # Authentik secrets
            create_secret_if_not_exists "authentik_postgresql_password" "${{ secrets.AUTHENTIK_POSTGRESQL_PASSWORD }}"
            create_secret_if_not_exists "authentik_secret_key" "${{ secrets.AUTHENTIK_SECRET_KEY }}"

            # Matomo secrets
            create_secret_if_not_exists "matomo_database_password" "${{ secrets.MATOMO_DATABASE_PASSWORD }}"
            create_secret_if_not_exists "matomo_mysql_root_password" "${{ secrets.MATOMO_MYSQL_ROOT_PASSWORD }}"

            # Existing secrets (for automation)
            create_secret_if_not_exists "s3_access_key" "${{ secrets.S3_ACCESS_KEY }}"
            create_secret_if_not_exists "s3_secret_key" "${{ secrets.S3_SECRET_KEY }}"
            create_secret_if_not_exists "stripe_secret_key" "${{ secrets.STRIPE_SECRET_KEY }}"
            create_secret_if_not_exists "stripe_webhook_secret" "${{ secrets.STRIPE_WEBHOOK_SECRET }}"

  deploy:
    name: Deploy to production
    needs: [sync-secrets]
    if: (github.event_name == 'push' && github.ref == 'refs/heads/main') || github.event_name == 'workflow_dispatch'
    runs-on: self-hosted
    environment:
      name: production
      url: https://freehunt.fr

    steps:
      - name: Deploy to production server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          debug: true
          script: |
            # Navigate to the project directory
            cd ${{ secrets.PROJECT_PATH }}

            # Pull the latest changes from the repository
            # git pull origin main
            git pull

            echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

            # Pull newest images 
            docker pull ghcr.io/$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')/freehunt-frontend:latest
            docker pull ghcr.io/$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')/freehunt-backend:latest

            # Redeploy the stack with newest images
            docker stack deploy -c compose.yaml -c compose.prod.yaml freehunt --with-registry-auth

            # Verify the deployment
            echo "État du déploiement:"
            docker stack services freehunt

            # Logout from registry
            docker logout ghcr.io
